version: "3"

services:

  crud-go_postgres:
    platform: linux/x86_64
    image: postgres:latest
    container_name: crud-go_postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - crud-go_network

networks:
  crud-go_network:
    external: true
