FROM golang:1.19.3-alpine
LABEL  maintainer "Dongri Jin <dongrify@gmail.com>"

RUN apk add --no-cache alpine-sdk
RUN go install github.com/githubnemo/CompileDaemon@latest

ADD . /go/src/github.com/dongri/crud-go/server
WORKDIR /go/src/github.com/dongri/crud-go/server

CMD PORT=3001 CompileDaemon -command="./server"
EXPOSE 3001
